{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kappamc.kapregh",
    "module": "Kapregh",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "Kapregh-1.1.0-SNAPSHOT.jar",
          "url": "Kapregh-1.1.0-SNAPSHOT.jar",
          "size": 83162,
          "sha512": "acb99f36f95bd19be84961f063619cd14330cddb583f034ec049c43a4ff10261c6a571fe319921ed0e86cd5383d54685df7fac77b05c500d298409135941d426",
          "sha256": "160abc661de868aec2c80887a60bb14dd8ec0a530677caa69562d909bdab32a3",
          "sha1": "50e5b4257d20282c08c6678796bbf706f7a3ae47",
          "md5": "eaaef5e6746a6bb312889b2fc76885ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "Kapregh-1.1.0-SNAPSHOT.jar",
          "url": "Kapregh-1.1.0-SNAPSHOT.jar",
          "size": 83162,
          "sha512": "acb99f36f95bd19be84961f063619cd14330cddb583f034ec049c43a4ff10261c6a571fe319921ed0e86cd5383d54685df7fac77b05c500d298409135941d426",
          "sha256": "160abc661de868aec2c80887a60bb14dd8ec0a530677caa69562d909bdab32a3",
          "sha1": "50e5b4257d20282c08c6678796bbf706f7a3ae47",
          "md5": "eaaef5e6746a6bb312889b2fc76885ba"
        }
      ]
    }
  ]
}
